# create logistic regression to predict absenteeism

In [1]:
import numpy as np 
import pandas as pd

## load data 

In [2]:
data_preprocess= pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed = data_preprocess.copy()

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

In [5]:
 targets = np.where(data_preprocessed['Absenteeism Time in Hours']>
   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['lai absent '] = targets


In [7]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0                 30          0         2    1                          4   
1                 31          0         1    0                          0   
2                 31          0         0    0                          2   
3                 24          0         2    0                          4   
4                 30          0         2    1                          2   
..               ...        ...       ...  ...                        ...   
695               22          1         2    0                          8   
696               24          0         1    2                          3   
697               25          1         0    0                          8   
698               25          1         0    0                          2   
699               25          0         1    1                          2   

     lai absent   
0              1  
1              0  
2              0  
3              1  
4              0  
..           ...  
695            1  
696            0  
697            1  
698            0  
699            0  

[700 rows x 16 columns]

In [8]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Distance to Work',
                   'Daily Work Load Average'] , axis = 1)

In [9]:
data_with_targets

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                       289   33               30          0         2    1   
1                       118   50               31          0         1    0   
2                       179   38               31          0         0    0   
3                       279   39               24          0         2    0   
4                       289   33               30          0         2    1   
..                      ...  ...              ...        ...       ...  ...   
695                     179   40               22          1         2    0   
696                     225   28               24          0         1    2   
697                     330   28               25          1         0    0   
698                     235   32               25          1         0    0   
699                     291   40               25          0         1    1   

     lai absent   
0              1  
1              0  
2              0  
3              1  
4              0  
..           ...  
695            1  
696            0  
697            1  
698            0  
699            0  

[700 rows x 12 columns]

## select the inputs for regression 

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

In [12]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [13]:
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]


## standardize the data

In [14]:
from sklearn.preprocessing  import StandardScaler
absenteeism_scaler = StandardScaler()

In [15]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin): 
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [16]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

C:\Users\vaibhav patil\anaconda323\envs\tensorflow_env\lib\site-packages\sklearn\utils\validation.py:72: FutureWarning: Pass copy=True, with_mean=True, with_std=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.030796   
1           0         0         0         0     0.030796   
2           0         0         0         1     0.030796   
3           1         0         0         0     0.030796   
4           0         0         0         1     0.030796   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.568019   
696         1         0         0         0    -0.568019   
697         1         0         0         0    -0.568019   
698         0         0         0         1    -0.568019   
699         0         0         0         1    -0.568019   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

          Pet  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

## split the data into train and test and shuffle 

In [22]:
from sklearn.model_selection import train_test_split

## split

In [23]:
train_test_split(scaled_inputs, targets , train_size = 0.8 )

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 412         0         0         0         1    -0.568019   
 633         0         0         0         1    -1.166834   
 114         0         0         1         0    -0.867426   
 18          1         0         0         0     0.030796   
 310         1         0         0         0     0.929019   
 ..        ...       ...       ...       ...          ...   
 673         0         0         0         1    -0.867426   
 116         0         0         1         0    -0.568019   
 444         0         0         0         1     0.330204   
 103         0         0         0         1    -0.867426   
 127         0         0         0         1     1.228426   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 412               -0.654143  0.248310         1.002633          0 -0.919030   
 633               -0.654143 -1.006686        -1.819793          1 -0.919030   
 114               -1.5746

In [24]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs, targets , train_size = 0.8 )

In [25]:
x_train.shape

(560, 11)

In [26]:
x_test.shape

(140, 11)

In [27]:
y_train.shape

(560,)

In [28]:
y_test.shape

(140,)

## logistic regression with sklearn

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [30]:
reg =  LogisticRegression()

In [31]:
reg.fit(x_train,y_train)

LogisticRegression()

In [32]:
reg.score(x_train,y_train)

0.7821428571428571

## manually check the accuracy

In [33]:
model_outputs = reg.predict(x_train)

In [34]:
model_outputs

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,

In [35]:
y_train

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [36]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True, False,  True,  True, False,  True, False,  True,  True,
       False, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,

In [37]:
np.sum(model_outputs == y_train)

438

In [38]:
model_outputs.shape

(560,)

In [39]:
## there no of np.sum(model_outputs == y_train) i.e 436 means no of equals going the divide by total no so the
##result is accuracy 

In [40]:
np.sum(model_outputs == y_train)/ 560

0.7821428571428571

## finding the intercept and coefficient 

In [41]:
reg.coef_

array([[ 2.90290771,  0.66537302,  3.02925339,  0.88732014, -0.01606661,
         0.6021111 , -0.19918354,  0.27638201, -0.01535042,  0.4174112 ,
        -0.36342071]])

In [42]:
reg.intercept_

array([-1.68170634])

In [43]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [44]:
featrues = unscaled_inputs.columns.values

In [45]:
summary_table = pd.DataFrame(columns=['featrues'], data=featrues)

summary_table['Coefficient']= np.transpose(reg.coef_)\

summary_table

featrues  Coefficient
0                 Reason_1     2.902908
1                 Reason_2     0.665373
2                 Reason_3     3.029253
3                 Reason_4     0.887320
4              Month Value    -0.016067
5   Transportation Expense     0.602111
6                      Age    -0.199184
7          Body Mass Index     0.276382
8                Education    -0.015350
9                 Children     0.417411
10                     Pet    -0.363421

In [46]:
summary_table.index = summary_table.index+1 
summary_table.loc[0] = ['intercept' , reg.intercept_[0]]
summary_table= summary_table.sort_index()
summary_table

featrues  Coefficient
0                intercept    -1.681706
1                 Reason_1     2.902908
2                 Reason_2     0.665373
3                 Reason_3     3.029253
4                 Reason_4     0.887320
5              Month Value    -0.016067
6   Transportation Expense     0.602111
7                      Age    -0.199184
8          Body Mass Index     0.276382
9                Education    -0.015350
10                Children     0.417411
11                     Pet    -0.363421

## interpreting the coefficients

In [47]:
summary_table['odds_ratio'] = np.exp(summary_table.Coefficient)


In [48]:
summary_table

featrues  Coefficient  odds_ratio
0                intercept    -1.681706    0.186056
1                 Reason_1     2.902908   18.227067
2                 Reason_2     0.665373    1.945216
3                 Reason_3     3.029253   20.681786
4                 Reason_4     0.887320    2.428613
5              Month Value    -0.016067    0.984062
6   Transportation Expense     0.602111    1.825970
7                      Age    -0.199184    0.819399
8          Body Mass Index     0.276382    1.318351
9                Education    -0.015350    0.984767
10                Children     0.417411    1.518027
11                     Pet    -0.363421    0.695294

In [49]:
summary_table.sort_values('odds_ratio', ascending = False)

featrues  Coefficient  odds_ratio
3                 Reason_3     3.029253   20.681786
1                 Reason_1     2.902908   18.227067
4                 Reason_4     0.887320    2.428613
2                 Reason_2     0.665373    1.945216
6   Transportation Expense     0.602111    1.825970
10                Children     0.417411    1.518027
8          Body Mass Index     0.276382    1.318351
9                Education    -0.015350    0.984767
5              Month Value    -0.016067    0.984062
7                      Age    -0.199184    0.819399
11                     Pet    -0.363421    0.695294
0                intercept    -1.681706    0.186056

In [50]:
reg.score(x_test , y_test)

0.7214285714285714

In [51]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.75354867, 0.24645133],
       [0.75234588, 0.24765412],
       [0.75768438, 0.24231562],
       [0.92771753, 0.07228247],
       [0.45950496, 0.54049504],
       [0.45472992, 0.54527008],
       [0.13412393, 0.86587607],
       [0.139232  , 0.860768  ],
       [0.75265421, 0.24734579],
       [0.56879971, 0.43120029],
       [0.41938283, 0.58061717],
       [0.40257154, 0.59742846],
       [0.40257154, 0.59742846],
       [0.39450011, 0.60549989],
       [0.39912561, 0.60087439],
       [0.17697801, 0.82302199],
       [0.86280915, 0.13719085],
       [0.41319763, 0.58680237],
       [0.74800648, 0.25199352],
       [0.17838372, 0.82161628],
       [0.57586427, 0.42413573],
       [0.20378062, 0.79621938],
       [0.34618133, 0.65381867],
       [0.74724185, 0.25275815],
       [0.7514485 , 0.2485515 ],
       [0.28161956, 0.71838044],
       [0.70516447, 0.29483553],
       [0.38440444, 0.61559556],
       [0.74814933, 0.25185067],
       [0.6194337 , 0.3805663 ],
       [0.

In [52]:
predict_proba.shape

(140, 2)

## save the model

In [53]:
import pickle

In [54]:
with open('model','wb') as file:
          pickle.dump(reg,file)       

In [55]:
with open('scaler' , 'wb') as file :
    pickle.dump(absenteeism_scaler, file)

In [56]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin


class CustomScaler(BaseEstimator,TransformerMixin): 
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler = StandardScaler(copy,with_mean,with_std)
        self.columns = columns
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.array(np.mean(X[self.columns]))
        self.var_ = np.array(np.var(X[self.columns]))
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]



class absenteeism_model():
      
        def __init__(self, model_file, scaler_file):
            with open('model','rb') as model_file, open('scaler', 'rb') as scaler_file:
                self.reg = pickle.load(model_file)
                self.scaler = pickle.load(scaler_file)
                self.data = None
        
        def load_and_clean_data(self, data_file):
            
            df = pd.read_csv(data_file,delimiter=',')
            self.df_with_predictions = df.copy()
            df = df.drop(['ID'], axis = 1)
            df['Absenteeism Time in Hours'] = 'NaN'

            reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)

            reason_type_1 = reason_columns.loc[:,1:14].max(axis=1)
            reason_type_2 = reason_columns.loc[:,15:17].max(axis=1)
            reason_type_3 = reason_columns.loc[:,18:21].max(axis=1)
            reason_type_4 = reason_columns.loc[:,22:].max(axis=1)

            df = df.drop(['Reason for Absence'], axis = 1)
            df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)
            
            column_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
                           'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
                           'Pet', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']
            df.columns = column_names

            column_names_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 
                                      'Distance to Work', 'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education', 
                                      'Children', 'Pet', 'Absenteeism Time in Hours']
            df = df[column_names_reordered]

            df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

            list_months = []
            for i in range(df.shape[0]):
                list_months.append(df['Date'][i].month)

            df['Month Value'] = list_months

            df['Day of the Week'] = df['Date'].apply(lambda x: x.weekday())

            df = df.drop(['Date'], axis = 1)

            # re-order the columns in df
            column_names_upd = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value', 'Day of the Week',
                                'Transportation Expense', 'Distance to Work', 'Age',
                                'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
                                'Pet', 'Absenteeism Time in Hours']
            df = df[column_names_upd]
            df['Education'] = df['Education'].map({1:0, 2:1, 3:1, 4:1})
            df = df.fillna(value=0)
            df = df.drop(['Absenteeism Time in Hours'],axis=1)
            df = df.drop(['Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)
            self.preprocessed_data = df.copy()
            self.data = self.scaler.transform(df)
            
        def predicted_probability(self):
            if (self.data is not None):  
                pred = self.reg.predict_proba(self.data)[:,1]
                return pred

        def predicted_output_category(self):
            if (self.data is not None):
                pred_outputs = self.reg.predict(self.data)
                return pred_outputs

        def predicted_outputs(self):
            if (self.data is not None):
                self.preprocessed_data['Probability'] = self.reg.predict_proba(self.data)[:,1]
                self.preprocessed_data ['Prediction'] = self.reg.predict(self.data)
                return self.preprocessed_data
